version: '3.3'

services:
  db:
    image: mysql:5
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_DATABASE: "DbTest"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
  phpMyAdmin:
    image: phpmyadmin
    # restart: always
    ports:
      - 5050:80
    environment:
      - PMA_HOST=mysql
